### ISSUE TITLE
second monitor still has a round corner

### ISSUE THREAD

**Issue by mipmip** [ogarcia/remove-rounded-corners#2]

**Comment by ogarcia** [comment]
@mipmip are you using an extension to show top bar in second monitor?

**Comment by mipmip** [comment]
yes I'm using Dash to Panel.

**Comment by ogarcia** [comment]
This is the problem. Second top bar is managed by Dash to Panel instead of use standard panel settings. I think that you should open this issue in Dash to Panel repository.

**Comment by mipmip** [comment]
That sound logical, though Just Perfection did it on both monitors together with Dash to Panel. Would you be interested in a PR for Dash to Panel compatibility with two monitors?

**Comment by ogarcia** [comment]
This extension is for the standard bar with minimalist code, I can evaluate the PR but if it depends of have or not other extension installed then I cannot merge it.

**Comment by ogarcia** [comment]
New version _4_ uploaded to https://extensions.gnome.org/extension/4201/remove-rounded-corners/ is now in review. In next hours will be appear to download or install. :wink:

**Comment by mipmip** [comment]
Thanks!

**Comment by mipmip** [comment]
I love tiny extensions.
