### ISSUE TITLE
Gnome 42 support

### ISSUE THREAD

**Issue by jhpratt** [ogarcia/remove-rounded-corners#5]
With Fedora 36 beta coming out soon, would you mind updating this extension to support Gnome 42?

**Comment by ogarcia** [comment]
Yes, but first GNOME 42 must be a stable release before perform update

**Comment by jhpratt** [comment]
Looks like Gnome 42 was fully released a day or two ago.

**Comment by ogarcia** [comment]
For now GNOME 42 [is not available for any (stable) distribution][1]. In any case I have tested the Fedora 36 beta and as far as I can see it has straight corners, so this extension no longer makes sense.

![Fedora 36 screenshot](https://user-images.githubusercontent.com/572924/160234874-37345cfe-ff2f-489d-8e6a-0e0153b23c89.png)

Anyway, as soon as GNOME 42 is available on Arch Linux I will check it and, if the extension is still needed, I will update it.

[1]: https://www.gnome.org/getting-gnome/

**Comment by jhpratt** [comment]
Oh neat! Even better in that situation. I plan on installing the beta the day it's released (Tuesday).

Thank you for your quick responses!

**Comment by ogarcia** [comment]
After testing GNOME version 42 on a couple of different distributions I can confirm that this extension is no longer needed since the corners are no longer rounded.

If at some point in the future the situation changes I will develop a new version of this extension, but for now it is on hold.
